# API 版本，这里是 v1
apiVersion: v1
# 资源类型，是 PersistentVolumeClaim
kind: PersistentVolumeClaim
# 资源的元数据
metadata:
  # 资源的名称，这里是 webook-mysql-pvc
  name: webook-mysql-pvc
# PVC 的具体信息
spec:
  # 存储类，用于指定 PVC 的存储类型，这里是 record
  storageClassName: record
  # 访问模式，ReadWriteOnce 表示只有一个节点可以读写挂载这个 PVC 的卷，这里设置为了 ReadWriteOnce
  accessModes:
    - ReadWriteOnce
  # 资源请求，描述了这个 PVC 需要的存储资源大小，这里请求了 1Gi 的存储空间
  resources:
    requests:
      storage: 1Gi
